services:
  - type: web
    name: youtube-transcript-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: WEBSHARE_PROXY_USERNAME
        sync: false
      - key: WEBSHARE_PROXY_PASSWORD
        sync: false
      - key: PORT
        value: 10000
    autoDeploy: true
